name: build
on:
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to Maven/Curseforge/Modrinth'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set Commit Hash
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Setup Permissions
        run: chmod +x ./gradlew

      - name: Build
        run: |
          if [ "${{ inputs.publish }}" = "true" ]; then
            ./gradlew clean assemble --stacktrace
          else
            ./gradlew assemble --stacktrace -PcommitHash="${{ env.SHORT_SHA }}"
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-${{ env.SHORT_SHA }}
          path: build/libs/

      - name: Publish to Maven
        if: ${{ inputs.publish }}
        run: ./gradlew publish --stacktrace -PCrystaelixMavenUsername="${{ secrets.MAVEN_USERNAME }}" -PCrystaelixMavenPassword="${{ secrets.MAVEN_PASSWORD }}"

      - name: Publish to Curseforge/Modrinth
        if: ${{ inputs.publish }}
        run: ./gradlew publishMods --stacktrace -Pcurseforge.token="${{ secrets.CURSEFORGE_TOKEN }}" -Pmodrinth.token="${{ secrets.MODRINTH_TOKEN }}"
